"""empty message

Revision ID: 1463df737435
Revises: ccfff9430c0e
Create Date: 2024-02-14 13:49:55.178484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1463df737435'
down_revision = 'ccfff9430c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quest_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('death', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_column('death')
        batch_op.drop_column('quest_type')

    # ### end Alembic commands ###
