"""empty message

Revision ID: ccfff9430c0e
Revises: 4bf58cfebaf2
Create Date: 2024-02-14 10:50:06.022073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfff9430c0e'
down_revision = '4bf58cfebaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
